<?php

use Illuminate\Database\Seeder;
use App\Course;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('courses')->insert([
            ['career_id' => 3, 'code'=> 'BBI01','title' => 'Quimica General',      ],
            ['career_id' => 3, 'code'=> 'BBI02','title' => 'Fisica I',      ],
            ['career_id' => 3, 'code'=> 'BBI03','title' => 'Matematica I',      ],
            ['career_id' => 3, 'code'=> 'BBI04','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 3, 'code'=> 'BBI05','title' => 'Quimica Organica',      ],
            ['career_id' => 3, 'code'=> 'BBI06','title' => 'Fisica II',      ],
            ['career_id' => 3, 'code'=> 'BBI07','title' => 'Matematica II',      ],
            ['career_id' => 3, 'code'=> 'BBI08','title' => 'Informatica',      ],
            ['career_id' => 3, 'code'=> 'BBI09','title' => 'Bioestadistica',      ],
            ['career_id' => 3, 'code'=> 'BBI10','title' => 'Quimica Organica I',      ],
            ['career_id' => 3, 'code'=> 'BBI11','title' => 'Fisico Quimica',      ],
            ['career_id' => 3, 'code'=> 'BBI12','title' => 'Quimica Analitica Y General',      ],
            ['career_id' => 3, 'code'=> 'BBI13','title' => 'Quimica Organica II',      ],
            ['career_id' => 3, 'code'=> 'BBI14','title' => 'Biologia General y Celular',      ],
            ['career_id' => 3, 'code'=> 'BBI16','title' => 'Quimics Biologica',      ],
            ['career_id' => 3, 'code'=> 'BBI17','title' => 'Anatomo - Histologia',      ],
            ['career_id' => 3, 'code'=> 'BBI18','title' => 'Metodologia de la Investigacion',      ],
            ['career_id' => 3, 'code'=> 'BBI19','title' => 'Fisiologia Humana',      ],
            ['career_id' => 3, 'code'=> 'BBI20','title' => 'Microbiologia General',      ],
            ['career_id' => 3, 'code'=> 'BBI21','title' => 'Biologia Molecular',      ],
            ['career_id' => 3, 'code'=> 'BBI22','title' => 'Biofisca',      ],
            ['career_id' => 3, 'code'=> 'BBI23','title' => 'Inmunologia General',      ],
            ['career_id' => 3, 'code'=> 'BBI24','title' => 'Patalogia Humana',      ],
            ['career_id' => 3, 'code'=> 'BBI25','title' => 'Quimica Anal. Clinica',      ],
            ['career_id' => 3, 'code'=> 'BBI26','title' => 'Bacteotologia y Virologia',      ],
            ['career_id' => 3, 'code'=> 'BBI27','title' => 'Farmacologia',      ],
            ['career_id' => 3, 'code'=> 'BBI28','title' => 'Analisis Clinicos',      ],
            ['career_id' => 3, 'code'=> 'BBI30','title' => 'Bromatologia',      ],
            ['career_id' => 3, 'code'=> 'BBI31','title' => 'Parasitologia y Micologia',      ],
            ['career_id' => 3, 'code'=> 'BBI32','title' => 'Toxicologia y Qca. Legal',      ],
            ['career_id' => 3, 'code'=> 'BBI33','title' => 'Analisis Clinicos II',      ],
            ['career_id' => 3, 'code'=> 'BBI34','title' => 'Electiva I',      ],
            ['career_id' => 3, 'code'=> 'BBI35','title' => 'Practica Profesional',      ],
            ['career_id' => 3, 'code'=> 'BBI36','title' => 'Legislacion y Etica Profesional',      ],
            ['career_id' => 3, 'code'=> 'BBI37','title' => 'Electiva II',      ],
            ['career_id' =>3,'code'=> 'BBI38','title' => 'Practica Profesional',      ],
            ['career_id' =>4,'code'=> 'BFA01','title' => 'Quimica General',      ],
            ['career_id' =>4,'code'=> 'BFA02','title' => 'Fisica I',      ],
            ['career_id' =>4,'code'=> 'BFA03','title' => 'Matematica I',      ],
            ['career_id' =>4,'code'=> 'BFA04','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' =>4,'code'=> 'BFA05','title' => 'Quimica Inorganica',      ],
            ['career_id' =>4,'code'=> 'BFA06','title' => 'Fisica II',      ],
            ['career_id' =>4,'code'=> 'BFA07','title' => 'Matematica II',      ],
            ['career_id' =>4,'code'=> 'BFA08','title' => 'Informatica',      ],
            ['career_id' =>4,'code'=> 'BFA09','title' => 'Bioestadistica',      ],
            ['career_id' =>4,'code'=> 'BFA10','title' => 'Quimica Organica I',      ],
            ['career_id' =>4,'code'=> 'BFA11','title' => 'Fisico Quimica',      ],
            ['career_id' =>4,'code'=> 'BFA12','title' => 'Quimica Analitica',      ],
            ['career_id' =>4,'code'=> 'BFA13','title' => 'Quimica Organica II',      ],
            ['career_id' =>4,'code'=> 'BFA14','title' => 'Biologia General y Celular',      ],
            ['career_id' =>4,'code'=> 'BFA15','title' => 'Ingles',      ],
            ['career_id' =>4,'code'=> 'BFA16','title' => 'Quimica Biologica',      ],
            ['career_id' =>4,'code'=> 'BFA17','title' => 'Anatomo - Histologia',      ],
            ['career_id' =>4,'code'=> 'BFA18','title' => 'Metodologia de la Investigacion',      ],
            ['career_id' =>4,'code'=> 'BFA19','title' => 'Botanica',      ],
            ['career_id' =>4,'code'=> 'BFA20','title' => 'Fisiologia Humana',      ],
            ['career_id' =>4,'code'=> 'BFA21','title' => 'Microbiologia General',      ],
            ['career_id' =>4,'code'=> 'BFA22','title' => 'Farmacologia',      ],
            ['career_id' =>4,'code'=> 'BFA23','title' => 'Inmunologia General',      ],
            ['career_id' =>4,'code'=> 'BFA24','title' => 'Patalogia Humana',      ],
            ['career_id' =>4,'code'=> 'BFA25','title' => 'Farmacoquimica',      ],
            ['career_id' =>4,'code'=> 'BFA26','title' => 'Lesgilacion y Etica Profesional',      ],
            ['career_id' =>4,'code'=> 'BFA27','title' => 'Higiene y Salud Publica',      ],
            ['career_id' =>4,'code'=> 'BFA28','title' => 'FarmacoTecnia I',      ],
            ['career_id' =>4,'code'=> 'BFA29','title' => 'Bromatologia y Nutricion',      ],
            ['career_id' =>4,'code'=> 'BFA30','title' => 'Farmacologia I',      ],
            ['career_id' =>4,'code'=> 'BFA31','title' => 'Farmacologia II',      ],
            ['career_id' =>4,'code'=> 'BFA32','title' => 'Farmacotecnia II',      ],
            ['career_id' =>4,'code'=> 'BFA33','title' => 'Analisis Farmaceutico',      ],
            ['career_id' =>4,'code'=> 'BFA34','title' => 'Farmacia Clinica y Asistencial',      ],
            ['career_id' =>4,'code'=> 'BFA35','title' => 'Biotecnologia Farmaceutica',      ],
            ['career_id' =>4,'code'=> 'BFA36','title' => 'Electiva I',      ],
            ['career_id' =>4,'code'=> 'BFA37','title' => 'Electiva II',      ],
            ['career_id' =>4,'code'=> 'BFA38','title' => 'Practica Profesional',      ],
            ['career_id' => 26,'code'=> 'CME01','title' => 'Examen de Ingreso',      ],
            ['career_id' => 26,'code'=> 'CME02','title' => 'Anatomía Normal',      ],
            ['career_id' => 26,'code'=> 'CME03','title' => 'Química Biológica',      ],
            ['career_id' => 26,'code'=> 'CME04','title' => 'Salud Pública I',      ],
            ['career_id' => 26,'code'=> 'CME05','title' => 'Expresión Oral y Escrita',      ],
            ['career_id' => 26,'code'=> 'CME06','title' => 'Fisiología Humana',      ],
            ['career_id' => 26,'code'=> 'CME07','title' => 'Histología, Embriología y Genética',      ],
            ['career_id' => 26,'code'=> 'CME08','title' => 'Física Biomédica',      ],
            ['career_id' => 26,'code'=> 'CME09','title' => 'Salud Pública II',      ],
            ['career_id' => 26,'code'=> 'CME10','title' => 'Humanismo Médico',      ],
            ['career_id' => 26,'code'=> 'CME11','title' => 'Inglés',      ],
            ['career_id' => 26,'code'=> 'CME12','title' => 'Patología',      ],
            ['career_id' => 26,'code'=> 'CME13','title' => 'Parasitología y Micología Médica',      ],
            ['career_id' => 26,'code'=> 'CME14','title' => 'Medicina Psicosocial',      ],
            ['career_id' => 26,'code'=> 'CME15','title' => 'Epistemología e Introducción a la Investigacion',      ],
            ['career_id' => 26,'code'=> 'CME16','title' => 'Medicina Antropológica',      ],
            ['career_id' => 26,'code'=> 'CME17','title' => 'Bacteriología y Virología Médica',      ],
            ['career_id' => 26,'code'=> 'CME18','title' => 'Salud Pública III',      ],
            ['career_id' => 26,'code'=> 'CME19','title' => 'Bioinformática',      ],
            ['career_id' => 26,'code'=> 'CME20','title' => 'Clínica Médica I',      ],
            ['career_id' => 26,'code'=> 'CME21','title' => 'Clínica Ginecológica',      ],
            ['career_id' => 26,'code'=> 'CME22','title' => 'Farmacología Básica',      ],
            ['career_id' => 26,'code'=> 'CME23','title' => 'Clínica Oftalmológica',      ],
            [ 'career_id' => 26,'code'=>'CME24','title' => 'Clínica Infectológica',      ],
            [ 'career_id' => 26,'code'=>'CME25','title' => 'Salud Mental',      ],
            [ 'career_id' => 26,'code'=>'CME26','title' => 'Radiología y Diagnóstico por Imágenes',      ],
            [ 'career_id' => 26,'code'=>'CME27','title' => 'Bioética',      ],
            [ 'career_id' => 26,'code'=>'CME28','title' => 'Clínica Dermatológica',      ],
            [ 'career_id' => 26,'code'=>'CME29','title' => 'Clínica Neurológica',      ],
            [ 'career_id' => 26,'code'=>'CME30','title' => 'Salud Pública IV',      ],
            [ 'career_id' => 26,'code'=>'CME31','title' => 'Clínica Médica II',      ],
            [ 'career_id' => 26,'code'=>'CME32','title' => 'Clínica Quirúrgica I',      ],
            [ 'career_id' => 26,'code'=>'CME33','title' => 'Clínica Obstétrica y Perinatológica',      ],
            [ 'career_id' => 26,'code'=>'CME34','title' => 'Clínica Pediátrica',      ],
            [ 'career_id' => 26,'code'=>'CME35','title' => 'Clínica Traumatológica',      ],
            [ 'career_id' => 26,'code'=>'CME36','title' => 'Salud Pública V',      ],
            [ 'career_id' => 26,'code'=>'CME37','title' => 'Clínica Urológica',      ],
            [ 'career_id' => 26,'code'=>'CME38','title' => 'Farmacología Clínica',      ],
            [ 'career_id' => 26,'code'=>'CME39','title' => 'Medicina Legal y Toxicológica',      ],
            [ 'career_id' => 26,'code'=>'CME40','title' => 'Clínica Otorrinolaringológica',      ],
            ['career_id' => 8,'code'=> 'EIM01','title' => 'Algebra y Geometria Analitica',      ],
            ['career_id' => 8,'code'=> 'EIM02','title' => 'Analisis Matematico I',      ],
            ['career_id' => 8,'code'=> 'EIM03','title' => 'Fisica I',      ],
            ['career_id' => 8,'code'=> 'EIM04','title' => 'Informatica',      ],
            ['career_id' => 8,'code'=> 'EIM05','title' => 'Fundamentos de la Ingenieria',      ],
            ['career_id' => 8,'code'=> 'EIM06','title' => 'Quimica General e Inorganica',      ],
            ['career_id' => 8,'code'=> 'EIM07','title' => 'Sistemas de Representacion',      ],
            ['career_id' => 8,'code'=> 'EIM08','title' => 'Algoritmos y Estructuras de Datos',      ],
            ['career_id' => 8,'code'=> 'EIM09','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 8,'code'=> 'EIM10','title' => 'Estatica y Resistencia de Materiales',      ],
            ['career_id' => 8,'code'=> 'EIM11','title' => 'Ingles',      ],
            ['career_id' => 8,'code'=> 'EIM12','title' => 'Fisica II',      ],
            ['career_id' => 8,'code'=> 'EIM13','title' => 'Analisis Matematico II',      ],
            ['career_id' => 8,'code'=> 'EIM14','title' => 'Calculo Numerico',      ],
            ['career_id' => 8,'code'=> 'EIM15','title' => 'Probabilidad y Estadistica',      ],
            ['career_id' => 8,'code'=> 'EIM16','title' => 'Matematicas Avanzadas',      ],
            ['career_id' => 8,'code'=> 'EIM17','title' => 'Formacion de Emprendedores',      ],
            ['career_id' => 8,'code'=> 'EIM18','title' => 'Maquinas Electricas Industriales',      ],
            ['career_id' => 8,'code'=> 'EIM19','title' => 'Conocimiento y Ensayo de Materiales',      ],
            ['career_id' => 8,'code'=> 'EIM20','title' => 'Elementos de Maquinas',      ],
            ['career_id' => 8,'code'=> 'EIM21','title' => 'Laboratorio de Mediciones Electricas y Electronicas',      ],
            ['career_id' => 8,'code'=> 'EIM22','title' => 'Electrotenia',      ],
            ['career_id' => 8,'code'=> 'EIM23','title' => 'Termotecnia',      ],
            ['career_id' => 8,'code'=> 'EIM24','title' => 'Computacion y Complejidad Algoritmica',      ],
            ['career_id' => 8,'code'=> 'EIM25','title' => 'Fundamentos de Electronica Digital',      ],
            ['career_id' => 8,'code'=> 'EIM26','title' => 'Instalaciones Electricas Industriales',      ],
            ['career_id' => 8,'code'=> 'EIM27','title' => 'Modelo y Simulacion de Sistemas',      ],
            ['career_id' => 8,'code'=> 'EIM28','title' => 'Sistema de Tiempo Real',      ],
            ['career_id' => 8,'code'=> 'EIM29','title' => 'Automatizacion Industrial',      ],
            ['career_id' => 8,'code'=> 'EIM30','title' => 'Sistemas Digitales',      ],
            ['career_id' => 8,'code'=> 'EIM31','title' => 'Tecnologia Mecanica',      ],
            ['career_id' => 8,'code'=> 'EIM32','title' => 'Robotica Industrial I',      ],
            ['career_id' => 8,'code'=> 'EIM33','title' => 'Diseño de Sistemas Mecatronicos',      ],
            ['career_id' => 8,'code'=> 'EIM34','title' => 'Redes de Comunicacion Industrial',      ],
            ['career_id' => 8,'code'=> 'EIM35','title' => 'Tecnologia Industrial',      ],
            ['career_id' => 8,'code'=> 'EIM36','title' => 'Practica Profesional Supervisada',      ],
            ['career_id' => 8,'code'=> 'EIM37','title' => 'Gestion de Calidad',      ],
            ['career_id' => 8,'code'=> 'EIM38','title' => 'Control de Acondicionamientos Mecatronicos',      ],
            ['career_id' => 8,'code'=> 'EIM39','title' => 'Electiva I',      ],
            ['career_id' => 8,'code'=> 'EIM40','title' => 'Robotica Industrial II',      ],
            ['career_id' => 8,'code'=> 'EIM41','title' => 'Tecnologia Aplicada al Control de Sistemas Mecatronicos',      ],
            ['career_id' => 8,'code'=> 'EIM42','title' => 'Seguridad y Proteccion Industrial',      ],
            ['career_id' => 8,'code'=> 'EIM43','title' => 'Organizacion Industrial, Economia y Legislacion',      ],
            ['career_id' => 8,'code'=> 'EIM44','title' => 'Electiva II',      ],
            ['career_id' => 7,'code'=> 'EPM01','title' => 'Historia del Arte y el Diseño',      ],
            ['career_id' => 7,'code'=> 'EPM02','title' => 'Diseño Grafico',      ],
            ['career_id' => 7,'code'=> 'EPM03','title' => 'Fotografia E Iluminacion',      ],
            ['career_id' => 7,'code'=> 'EPM04','title' => 'Ingles I',      ],
            ['career_id' => 7,'code'=> 'EPM05','title' => 'Informatica',      ],
            ['career_id' => 7,'code'=> 'EPM06','title' => 'Comunicacion',      ],
            ['career_id' => 7,'code'=> 'EPM07','title' => 'Fundamentos de Programacion',      ],
            ['career_id' => 7,'code'=> 'EPM08','title' => 'Semiotica de la Imagen',      ],
            ['career_id' => 7,'code'=> 'EPM09','title' => 'Redes Multimediales',      ],
            ['career_id' => 7,'code'=> 'EPM10','title' => 'Sonido I',      ],
            ['career_id' => 7,'code'=> 'EPM11','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 7,'code'=> 'EPM12','title' => 'Programacion I',      ],
            ['career_id' => 7,'code'=> 'EPM13','title' => 'Imagen Digital I',      ],
            ['career_id' => 7,'code'=> 'EPM14','title' => 'Ingles II',      ],
            ['career_id' => 7,'code'=> 'EPM15','title' => 'Sonido II',      ],
            ['career_id' => 7,'code'=> 'EPM16','title' => 'Introduccion a la Publicidad',      ],
            ['career_id' => 7,'code'=> 'EPM17','title' => 'Imagen Digital II',      ],
            ['career_id' => 7,'code'=> 'EPM18','title' => 'Apliaciones Multimediales I',      ],
            ['career_id' => 7,'code'=> 'EPM19','title' => 'Narrativa y Guion',      ],
            ['career_id' => 7,'code'=> 'EPM20','title' => 'Arquitectura de la Informacion',      ],
            ['career_id' => 7,'code'=> 'EPM21','title' => 'Programacion II',      ],
            ['career_id' => 7,'code'=> 'EPM22','title' => 'Apliaciones Multimediales II',      ],
            ['career_id' => 7,'code'=> 'EPM23','title' => 'Animacion',      ],
            ['career_id' => 7,'code'=> 'EPM24','title' => 'Historia del Cine',      ],
            ['career_id' => 7,'code'=> 'EPM25','title' => 'Marketing Digital',      ],
            ['career_id' => 7,'code'=> 'EPM26','title' => 'Tecnicas Audiovisuales I',      ],
            ['career_id' => 7,'code'=> 'EPM27','title' => 'Desarrollo de Aplicaciones Multimediales',      ],
            ['career_id' => 7,'code'=> 'EPM28','title' => 'Tecnicas Audiovisuales II',      ],
            ['career_id' => 7,'code'=> 'EPM29','title' => 'Gestion de Empresas y Diseño',      ],
            ['career_id' => 7,'code'=> 'EPM30','title' => 'Montaje, Edicion y Postproduccion',      ],
            ['career_id' => 7,'code'=> 'EPM31','title' => 'Animacion Digital',      ],
            ['career_id' => 7,'code'=> 'EPM32','title' => 'Seminario de Actualizacion I',      ],
            ['career_id' => 7,'code'=> 'EPM33','title' => 'Asignatura Eletiva I',      ],
            ['career_id' => 7,'code'=> 'EPM34','title' => 'Television Digital y Nuevos Medios Multimediales',      ],
            ['career_id' => 7,'code'=> 'EPM35','title' => 'Diseño y Desarrollo de Videojuegos',      ],
            ['career_id' => 7,'code'=> 'EPM36','title' => 'Formacion de Emprendedores',      ],
            ['career_id' => 7,'code'=> 'EPM37','title' => 'Aplicaciones para Tecnologias Moviles',      ],
            ['career_id' => 7,'code'=> 'EPM38','title' => 'Eticas y Principios Juridicos del Diseño',      ],
            ['career_id' => 7,'code'=> 'EPM39','title' => 'Filosofia de las Artes Multimediales',      ],
            ['career_id' => 7,'code'=> 'EPM40','title' => 'Produccion y Direccion Artistica',      ],
            ['career_id' => 7,'code'=> 'EPM41','title' => 'Investigacion Aplicada',      ],
            ['career_id' => 7,'code'=> 'EPM42','title' => 'Tecnologias Multimediales para Desarrollos Educativos',      ],
            ['career_id' => 7,'code'=> 'EPM43','title' => 'Asignatura Electiva II',      ],
            ['career_id' => 7,'code'=> 'EPM44','title' => 'Seminario de Actualizacion II',      ],
            ['career_id' => 2,'code'=> 'ETB01','title' => 'Matematica',      ],
            ['career_id' => 2,'code'=> 'ETB02','title' => 'Quimica General e Inorganica',      ],
            ['career_id' => 2,'code'=> 'ETB03','title' => 'Fisica General',      ],
            ['career_id' => 2,'code'=> 'ETB04','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 2,'code'=> 'ETB05','title' => 'Quimica Organica',      ],
            ['career_id' => 2,'code'=> 'ETB06','title' => 'Ingles',      ],
            ['career_id' => 2,'code'=> 'ETB07','title' => 'Informatica',      ],
            ['career_id' => 2,'code'=> 'ETB08','title' => 'Bioestadistica',      ],
            ['career_id' => 2,'code'=> 'ETB09','title' => 'Quimica Biologica',      ],
            ['career_id' => 2,'code'=> 'ETB10','title' => 'Tecnologias de Laboratorio I',      ],
            ['career_id' => 2,'code'=> 'ETB11','title' => 'Biologia Celular',      ],
            ['career_id' => 2,'code'=> 'ETB12','title' => 'Biofisica',      ],
            ['career_id' => 2,'code'=> 'ETB13','title' => 'Genetica General',      ],
            ['career_id' => 2,'code'=> 'ETB14','title' => 'Microbiologia General',      ],
            ['career_id' => 2,'code'=> 'ETB15','title' => 'Genetica de los Microorganismos',      ],
            ['career_id' => 2,'code'=> 'ETB16','title' => 'Tecnologias de Laboratorio II',      ],
            ['career_id' => 2,'code'=> 'ETB17','title' => 'Bioseguridad',      ],
            ['career_id' => 2,'code'=> 'ETB18','title' => 'Genetica de Organismos Superiores',      ],
            ['career_id' => 2,'code'=> 'ETB19','title' => 'Biologia Molecular',      ],
            ['career_id' => 2,'code'=> 'ETB20','title' => 'Tecnologias de Laboratorio III',      ],
            ['career_id' => 2,'code'=> 'ETB21','title' => 'Practicanato',      ],
            ['career_id' => 5,'code'=> 'ISI01','title' => 'Algebra y Geometria Analitica',      ],
            ['career_id' => 5,'code'=> 'ISI03','title' => 'Ingles I',      ],
            ['career_id' => 5,'code'=> 'ISI04','title' => 'Informatica I',      ],
            ['career_id' => 5,'code'=> 'ISI05','title' => 'Quimica',      ],
            ['career_id' => 5,'code'=> 'ISI06','title' => 'Matematicas Discretas',      ],
            ['career_id' => 5,'code'=> 'ISI07','title' => 'Sistemas de Representacion',      ],
            ['career_id' => 5,'code'=> 'ISI08','title' => 'Informatica II',      ],
            ['career_id' => 5,'code'=> 'ISI09','title' => 'Algoritmos y Estructuras de Datos',      ],
            ['career_id' => 5,'code'=> 'ISI10','title' => 'Sistemas de Informacion I',      ],
            ['career_id' => 5,'code'=> 'ISI11','title' => 'Programacion I',      ],
            ['career_id' => 5,'code'=> 'ISI12','title' => 'Ingles II',      ],
            ['career_id' => 5,'code'=> 'ISI14','title' => 'Analisis Matematico II',      ],
            ['career_id' => 5,'code'=> 'ISI15','title' => 'Fisica I',      ],
            ['career_id' => 5,'code'=> 'ISI16','title' => 'Paradigmas de Programacion',      ],
            ['career_id' => 5,'code'=> 'ISI17','title' => 'Sistemas Operativos',      ],
            ['career_id' => 5,'code'=> 'ISI18','title' => 'Fisica II',      ],
            ['career_id' => 5,'code'=> 'ISI19','title' => 'Probabilidad y Estadistica',      ],
            ['career_id' => 5,'code'=> 'ISI20','title' => 'Analisis Matematico III',      ],
            ['career_id' => 5,'code'=> 'ISI21','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 5,'code'=> 'ISI22','title' => 'Sistemas de Informacion II',      ],
            ['career_id' => 5,'code'=> 'ISI23','title' => 'Programacion II',      ],
            ['career_id' => 5,'code'=> 'ISI24','title' => 'Computacion',      ],
            ['career_id' => 5,'code'=> 'ISI25','title' => 'Electronica Digital',      ],
            ['career_id' => 5,'code'=> 'ISI26','title' => 'Base de Datos',      ],
            ['career_id' => 5,'code'=> 'ISI27','title' => 'Arquictura Avanzada de Hardware',      ],
            ['career_id' => 5,'code'=> 'ISI28','title' => 'Adminitracion de Proyectos de Sistemas',      ],
            ['career_id' => 5,'code'=> 'ISI29','title' => 'Investigacion Operativa',      ],
            ['career_id' => 5,'code'=> 'ISI30','title' => 'Seminario de Actualizacion I',      ],
            ['career_id' => 5,'code'=> 'ISI31','title' => 'Redes de Datos I',      ],
            ['career_id' => 5,'code'=> 'ISI32','title' => 'Ingenieria de Software',      ],
            ['career_id' => 5,'code'=> 'ISI33','title' => 'Programacion III',      ],
            ['career_id' => 5,'code'=> 'ISI34','title' => 'Electiva I',      ],
            ['career_id' => 5,'code'=> 'ISI35','title' => 'Inteligencia Artificial',      ],
            ['career_id' => 5,'code'=> 'ISI36','title' => 'Redes de Datos II',      ],
            ['career_id' => 5,'code'=> 'ISI37','title' => 'Economia y Evaluacion de Proyectos',      ],
            ['career_id' => 5,'code'=> 'ISI38','title' => 'Sistemas Operativos Avanzados',      ],
            ['career_id' => 5,'code'=> 'ISI39','title' => 'Telematica',      ],
            ['career_id' => 5,'code'=> 'ISI40','title' => 'Metodologia de la Investigacion',      ],
            ['career_id' => 5,'code'=> 'ISI41','title' => 'Seminario de Actualizacion II',      ],
            ['career_id' => 5,'code'=> 'ISI42','title' => 'Electiva II',      ],
            ['career_id' => 5,'code'=> 'ISI43','title' => 'Practica Profesional Supervisada',      ],
            ['career_id' => 5,'code'=> 'ISI44','title' => 'Derecho Informatico y Etica Profesional',      ],
            ['career_id' => 5,'code'=> 'ISI45','title' => 'Modelo y Simulacion de Sistemas',      ],
            ['career_id' => 5,'code'=> 'ISI46','title' => 'Electiva III',      ],
            ['career_id' => 5,'code'=> 'ISI47','title' => 'Auditoria de Sistemas',      ],
            ['career_id' => 5,'code'=> 'ISI48','title' => 'Gestion Ambiental y Seguridad Ambiental',      ],
            ['career_id' => 5,'code'=> 'ISI49','title' => 'Calidad de Software',      ],
            ['career_id' => 5,'code'=> 'ISI50','title' => 'Seguridad Informatica',      ],
            ['career_id' => 5,'code'=> 'ISI51','title' => 'Seminario de Actualizacion III',      ],
            ['career_id' => 5,'code'=> 'ISI52','title' => 'Electiva IV',      ],
            ['career_id' => 5,'code'=> 'ISI53','title' => 'Trabajo Final',      ],
            ['career_id' => 6,'code'=> 'LSI01','title' => 'Algebra y Geometria Analitica',      ],
            ['career_id' => 6,'code'=> 'LSI02','title' => 'Analisis Matematico I',      ],
            ['career_id' => 6,'code'=> 'LSI03','title' => 'Ingles I',      ],
            ['career_id' => 6,'code'=> 'LSI04','title' => 'Informatica I',      ],
            ['career_id' => 6,'code'=> 'LSI05','title' => 'Logica',      ],
            ['career_id' => 6,'code'=> 'LSI06','title' => 'Informatica II',      ],
            ['career_id' => 6,'code'=> 'LSI07','title' => 'Algoritmos y Estructuras de Datos',      ],
            ['career_id' => 6,'code'=> 'LSI08','title' => 'Sistemas de Informacion I',      ],
            ['career_id' => 6,'code'=> 'LSI09','title' => 'Paradigmas y Lenguajes I',      ],
            ['career_id' => 6,'code'=> 'LSI10','title' => 'Ingles II',      ],
            ['career_id' => 6,'code'=> 'LSI11','title' => 'Admistracion',      ],
            ['career_id' => 6,'code'=> 'LSI12','title' => 'Computacion I',      ],
            ['career_id' => 6,'code'=> 'LSI13','title' => 'Analisis Matematico II',      ],
            ['career_id' => 6,'code'=> 'LSI14','title' => 'Computacion II',      ],
            ['career_id' => 6,'code'=> 'LSI15','title' => 'Sistemas Operativos',      ],
            ['career_id' => 6,'code'=> 'LSI16','title' => 'Probabilidad y Estadistica',      ],
            ['career_id' => 6,'code'=> 'LSI17','title' => 'Sistemas de Informacion II',      ],
            ['career_id' => 6,'code'=> 'LSI18','title' => 'Paradigmas y Lenguajes II',      ],
            ['career_id' => 6,'code'=> 'LSI19','title' => 'Expresion Oral y Escrita',      ],
            ['career_id' => 6,'code'=> 'LSI20','title' => 'Arquictectura de Hardware',      ],
            ['career_id' => 6,'code'=> 'LSI21','title' => 'Administracion de Proyectos de Sistemas',      ],
            ['career_id' => 6,'code'=> 'LSI22','title' => 'Base de Datos',      ],
            ['career_id' => 6,'code'=> 'LSI23','title' => 'Redes de Datos y Comunicaciones I',      ],
            ['career_id' => 6,'code'=> 'LSI24','title' => 'Gestion de Capital Humano',      ],
            ['career_id' => 6,'code'=> 'LSI25','title' => 'Paradigmas y Lenguajes III',      ],
            ['career_id' => 6,'code'=> 'LSI26','title' => 'Ingenieria de Software',      ],
            ['career_id' => 6,'code'=> 'LSI27','title' => 'Redes y Comunicaciones II',      ],
            ['career_id' => 6,'code'=> 'LSI28','title' => 'Auditoria de Sistemas',      ],
            ['career_id' => 6,'code'=> 'LSI29','title' => 'Seminario de Actualizacion I',      ],
            ['career_id' => 6,'code'=> 'LSI30','title' => 'Sistemas Operativos Avanzados',      ],
            ['career_id' => 6,'code'=> 'LSI31','title' => 'Investigacion Aplicada',      ],
            ['career_id' => 6,'code'=> 'LSI32','title' => 'Electiva I',      ],
            ['career_id' => 6,'code'=> 'LSI33','title' => 'Calidad de Software',      ],
            ['career_id' => 6,'code'=> 'LSI34','title' => 'Derecho Informatica y Etica Profesional',      ],
            ['career_id' => 6,'code'=> 'LSI35','title' => 'Seminario de Actualizacion II',      ],
            ['career_id' => 6,'code'=> 'LSI36','title' => 'Practica Profesional Supervisada',      ],
            ['career_id' => 6,'code'=> 'LSI37','title' => 'Electiva II',      ],
            ['career_id' => 6,'code'=> 'LSI38','title' => 'Trabajo Final',      ],
            ['career_id' => 39,'code'=> 'SAB01','title' => 'Introduccion al Derecho',      ],
            ['career_id' => 39,'code'=> 'SAB02','title' => 'Derecho Romano',      ],
            ['career_id' => 39,'code'=> 'SAB03','title' => 'Derecho Civil I',      ],
            ['career_id' => 39,'code'=> 'SAB04','title' => 'Introduccion a la Filosofia',      ],
            ['career_id' => 39,'code'=> 'SAB05','title' => 'Historia del Derecho',      ],
            ['career_id' => 39,'code'=> 'SAB06','title' => 'Economia Politica',      ],
            ['career_id' => 39,'code'=> 'SAB07','title' => 'Derecho Civil II',      ],
            ['career_id' => 39,'code'=> 'SAB08','title' => 'Derecho Politico',      ],
            ['career_id' => 39,'code'=> 'SAB09','title' => 'Finanzas y Derecho Tributario',      ],
            ['career_id' => 39,'code'=> 'SAB10','title' => 'Derecho Comercial I',      ],
            ['career_id' => 39,'code'=> 'SAB11','title' => 'Sociologia',      ],
            ['career_id' => 39,'code'=> 'SAB12','title' => 'Filosofia del Derecho',      ],
            ['career_id' => 39,'code'=> 'SAB13','title' => 'Derecho Civil III',      ],
            ['career_id' => 39,'code'=> 'SAB14','title' => 'Derecho Comercial II',      ],
            ['career_id' => 39,'code'=> 'SAB15','title' => 'Derecho Constitucional',      ],
            ['career_id' => 39,'code'=> 'SAB16','title' => 'Derecho Penal I',      ],
            ['career_id' => 39,'code'=> 'SAB17','title' => 'Derecho Internacional, Publico y Comunitario',      ],
            ['career_id' => 39,'code'=> 'SAB18','title' => 'Derecho Laboral y Previsional',      ],
            ['career_id' => 39,'code'=> 'SAB19','title' => 'Derecho Civil IV',      ],
            ['career_id' => 39,'code'=> 'SAB20','title' => 'Derecho Comercial III',      ],
            ['career_id' => 39,'code'=> 'SAB21','title' => 'Derecho Publico, Provincial y Municipal',      ],
            ['career_id' => 39,'code'=> 'SAB22','title' => 'Derecho Penal II',      ],
            ['career_id' => 39,'code'=> 'SAB23','title' => 'Derecho Procesal, Civil y Laboral',      ],
            ['career_id' => 39,'code'=> 'SAB24','title' => 'Derecho Agrario, Forestal y Minero',      ],
            ['career_id' => 39,'code'=> 'SAB25','title' => 'Derecho Civil V',      ],
            ['career_id' => 39,'code'=> 'SAB26','title' => 'Derecho de la Navegacion',      ],
            ['career_id' => 39,'code'=> 'SAB27','title' => 'Derecho Administrativo',      ],
            ['career_id' => 39,'code'=> 'SAB28','title' => 'Etica Profesional y Practica Forense',      ],
            ['career_id' => 39,'code'=> 'SAB29','title' => 'Derecho Procesal Penal',      ],
            ['career_id' => 39,'code'=> 'SAB30','title' => 'Derecho Internacional, Privado y Comunitario',      ],
            ['career_id' => 40,'code'=> 'SCO01','title' => 'Matemática I',      ],
            ['career_id' => 40,'code'=> 'SCO02','title' => 'Economía I',      ],
            ['career_id' => 40,'code'=> 'SCO03','title' => 'Sistemas de Información Contable I',      ],
            ['career_id' => 40,'code'=> 'SCO04','title' => 'Metetodología de Estudio de las Ciencias Sociales',      ],
            ['career_id' => 40,'code'=> 'SCO05','title' => 'Sistemas de Información Contable II',      ],
            ['career_id' => 40,'code'=> 'SCO06','title' => 'Economía II',      ],
            ['career_id' => 40,'code'=> 'SCO07','title' => 'Matemática II',      ],
            ['career_id' => 40,'code'=> 'SCO08','title' => 'Filosofía',      ],
            ['career_id' => 40,'code'=> 'SCO09','title' => 'Administración I',      ],
            ['career_id' => 40,'code'=> 'SCO10','title' => 'Derecho Público',      ],
            ['career_id' => 40,'code'=> 'SCO11','title' => 'Estadística',      ],
            ['career_id' => 40,'code'=> 'SCO12','title' => 'Sistemas de Información Contable III',      ],
            ['career_id' => 40,'code'=> 'SCO13','title' => 'Derecho Privado I –parte general-',      ],
            ['career_id' => 40,'code'=> 'SCO14','title' => 'Informática Básica Aplicada',      ],
            ['career_id' => 40,'code'=> 'SCO15','title' => 'Administración II',      ],
            ['career_id' => 40,'code'=> 'SCO16','title' => 'Economía III',      ],
            ['career_id' => 40,'code'=> 'SCO17','title' => 'Historia Social y Económica',      ],
            ['career_id' => 40,'code'=> 'SCO18','title' => 'Derecho Privado II –Civil y Comercial-',      ],
            ['career_id' => 40,'code'=> 'SCO19','title' => 'Sistemas de Información Contable IV',      ],
            ['career_id' => 40,'code'=> 'SCO20','title' => 'Cálculo Financiero y Actuarial',      ],
            ['career_id' => 40,'code'=> 'SCO21','title' => 'Derecho Privado III –Laboral y Seg.Soc',      ],
            ['career_id' => 40,'code'=> 'SCO22','title' => 'Finanzas Públicas',      ],
            ['career_id' => 40,'code'=> 'SCO23','title' => 'Análisis de los estados Contables',      ],
            ['career_id' => 40,'code'=> 'SCO24','title' => 'Comportamiento Organizacional de los Recursos',      ],
            ['career_id' => 40,'code'=> 'SCO25','title' => 'Derecho Financiero y Tributario',      ],
            ['career_id' => 40,'code'=> 'SCO26','title' => 'Sistemas Impositivos I',      ],
            ['career_id' => 40,'code'=> 'SCO27','title' => 'Auditoria Contable y Operativa',      ],
            ['career_id' => 40,'code'=> 'SCO28','title' => 'Administración Financiera',      ],
            ['career_id' => 40,'code'=> 'SCO29','title' => 'Derecho Privado IV – Societario y Concursal -',      ],
            ['career_id' => 40,'code'=> 'SCO30','title' => 'Sistemas Impositivos II',      ],
            ['career_id' => 40,'code'=> 'SCO31','title' => 'Contabilidad Pública',      ],
            ['career_id' => 44,'code'=> 'SCP01','title' => 'Filosofia',      ],
            ['career_id' => 44,'code'=> 'SCP02','title' => 'Derecho Privado',      ],
            ['career_id' => 44,'code'=> 'SCP03','title' => 'Historia del Pensamiento Político I',      ],
            ['career_id' => 44,'code'=> 'SCP04','title' => 'Teorias y Tecnicas De Investigación en Cienci',      ],
            ['career_id' => 44,'code'=> 'SCP05','title' => 'Ciencia Política',      ],
            ['career_id' => 44,'code'=> 'SCP06','title' => 'Geografia Económica',      ],
            ['career_id' => 44,'code'=> 'SCP07','title' => 'Economia I',      ],
            ['career_id' => 44,'code'=> 'SCP08','title' => 'Historia del Pensamiento Político II',      ],
            ['career_id' => 44,'code'=> 'SCP09','title' => 'Sociología Política',      ],
            ['career_id' => 44,'code'=> 'SCP10','title' => 'Derecho Constitucional',      ],
            ['career_id' => 44,'code'=> 'SCP11','title' => 'Historia Política e Institucional Argentina',      ],
            ['career_id' => 44,'code'=> 'SCP12','title' => 'Técnicas de Expresión Oral y Escrita',      ],
            ['career_id' => 44,'code'=> 'SCP13','title' => 'Teoría Política',      ],
            ['career_id' => 44,'code'=> 'SCP14','title' => 'Geopolítica',      ],
            ['career_id' => 44,'code'=> 'SCP15','title' => 'Economía II',      ],
            ['career_id' => 44,'code'=> 'SCP16','title' => 'Derecho Administrativo y Ciencia de la Admini',      ],
            ['career_id' => 44,'code'=> 'SCP17','title' => 'Problemática social y política Americana',      ],
            ['career_id' => 44,'code'=> 'SCP18','title' => 'Finanzas Publicas',      ],
            ['career_id' => 44,'code'=> 'SCP19','title' => 'Planeamiento',      ],
            ['career_id' => 44,'code'=> 'SCP20','title' => 'Análisis Político',      ],
            ['career_id' => 44,'code'=> 'SCP21','title' => 'Regímenes y Sistemas Políticos Comparados',      ],
            ['career_id' => 44,'code'=> 'SCP22','title' => 'Teoría de la Información y Comunicación',      ],
            ['career_id' => 44,'code'=> 'SCP23','title' => 'Seminario I',      ],
            ['career_id' => 44,'code'=> 'SCP24','title' => 'Derecho Internacional Público',      ],
            ['career_id' => 44,'code'=> 'SCP25','title' => 'Política Internacional',      ],
            ['career_id' => 44,'code'=> 'SCP26','title' => 'Análisis y Planificación de Políticas Publica',      ],
            ['career_id' => 44,'code'=> 'SCP27','title' => 'Programación y Evaluación de Proyectos',      ],
            ['career_id' => 44,'code'=> 'SCP28','title' => 'Historia Política de los Estados Modernos',      ],
            ['career_id' => 44,'code'=> 'SCP29','title' => 'Teoría de la Administración Pública',      ],
            ['career_id' => 44,'code'=> 'SCP30','title' => 'Seminario II',      ],
            ['career_id' => 41,'code'=> 'SES01','title' => 'Introducción al Derecho',      ],
            ['career_id' => 41,'code'=> 'SES02','title' => 'Derecho Romano',      ],
            ['career_id' => 41,'code'=> 'SES03','title' => 'Derecho Civil I [Parte General]',      ],
            ['career_id' => 41,'code'=> 'SES04','title' => 'Economia Politica',      ],
            ['career_id' => 41,'code'=> 'SES05','title' => 'Derecho Civil II [obligaciones]',      ],
            ['career_id' => 41,'code'=> 'SES06','title' => 'Derecho Politico',      ],
            ['career_id' => 41,'code'=> 'SES07','title' => 'Finanzas y Derecho Tributario',      ],
            ['career_id' => 41,'code'=> 'SES08','title' => 'Derecho Comercial I',      ],
            ['career_id' => 41,'code'=> 'SES09','title' => 'Derecho Civil III [Contratos]',      ],
            ['career_id' => 41,'code'=> 'SES10','title' => 'Derecho Comercial II [Sociedades]',      ],
            ['career_id' => 41,'code'=> 'SES11','title' => 'Derecho Constitucional',      ],
            ['career_id' => 41,'code'=> 'SES12','title' => 'Derecho Penal I [Parte General]',      ],
            ['career_id' => 41,'code'=> 'SES13','title' => 'Derecho Internacional Publico y Comunitario',      ],
            ['career_id' => 41,'code'=> 'SES14','title' => 'Derecho Laboral y Previsional',      ],
            ['career_id' => 41,'code'=> 'SES15','title' => 'Derecho Civil IV [Derechos reales]',      ],
            ['career_id' => 41,'code'=> 'SES16','title' => 'Derecho Comercial III [Quiebras]',      ],
            ['career_id' => 41,'code'=> 'SES17','title' => 'Derecho Publico, Provincial y Municipal',      ],
            ['career_id' => 41,'code'=> 'SES18','title' => 'Derecho Penal II [parte especial]',      ],
            ['career_id' => 41,'code'=> 'SES19','title' => 'Derecho Procesal Civil y Laboral',      ],
            ['career_id' => 41,'code'=> 'SES20','title' => 'Derecho Agrario, Forestal y Minero',      ],
            ['career_id' => 41,'code'=> 'SES21','title' => 'Derecho Civil V [Familia y Sucesiones]',      ],
            ['career_id' => 41,'code'=> 'SES22','title' => 'Derecho de la Navegación',      ],
            ['career_id' => 41,'code'=> 'SES23','title' => 'Derecho Administrativo',      ],
            ['career_id' => 41,'code'=> 'SES24','title' => 'Derecho Procesal Penal',      ],
            ['career_id' => 41,'code'=> 'SES25','title' => 'Derecho Internacional Privado y Comunitario',      ],
            ['career_id' => 41,'code'=> 'SES26','title' => 'Derecho Notarial I',      ],
            ['career_id' => 41,'code'=> 'SES27','title' => 'Practica Notarial I',      ],
            ['career_id' => 41,'code'=> 'SES28','title' => 'Derecho Notarial II',      ],
            ['career_id' => 41,'code'=> 'SES29','title' => 'Practica Notarial II',      ],
            ['career_id' => 41,'code'=> 'SES30','title' => 'Derecho Registral',      ],
            ['career_id' => 41,'code'=> 'SES31','title' => 'Derecho Administrativo Notarial',      ],
            ['career_id' => 41,'code'=> 'SES32','title' => 'Teoria General del Negocio Juridico',      ],
            ['career_id' => 41,'code'=> 'SES33','title' => 'Etica Profesional y Practica Notarial',      ],
            ['career_id' => 42,'code'=> 'SLA01','title' => 'Matemática I',      ],
            ['career_id' => 42,'code'=> 'SLA02','title' => 'Economía I',      ],
            ['career_id' => 42,'code'=> 'SLA03','title' => 'Sistemas de Información Contable I',      ],
            ['career_id' => 42,'code'=> 'SLA04','title' => 'Metetodología de Estudio de las Ciencias Soci',      ],
            ['career_id' => 42,'code'=> 'SLA05','title' => 'Sistemas de Información Contable II',      ],
            ['career_id' => 42,'code'=> 'SLA06','title' => 'Economía II',      ],
            ['career_id' => 42,'code'=> 'SLA07','title' => 'Matemática II',      ],
            ['career_id' => 42,'code'=> 'SLA08','title' => 'Filosofía',      ],
            ['career_id' => 42,'code'=> 'SLA09','title' => 'Administración I',      ],
            ['career_id' => 42,'code'=> 'SLA10','title' => 'Derecho Público',      ],
            ['career_id' => 42,'code'=> 'SLA11','title' => 'Estadística',      ],
            ['career_id' => 42,'code'=> 'SLA12','title' => 'Sistemas de Información Contable III',      ],
            ['career_id' => 42,'code'=> 'SLA13','title' => 'Derecho Privado I –Parte General-',      ],
            ['career_id' => 42,'code'=> 'SLA14','title' => 'Informática Básica Aplicada',      ],
            ['career_id' => 42,'code'=> 'SLA15','title' => 'Administración II',      ],
            ['career_id' => 42,'code'=> 'SLA16','title' => 'Economía III',      ],
            ['career_id' => 42,'code'=> 'SLA17','title' => 'Historia Social y Económica',      ],
            ['career_id' => 42,'code'=> 'SLA18','title' => 'Cálculo Financiero y Actuarial',      ],
            ['career_id' => 42,'code'=> 'SLA19','title' => 'Contabilidad Gerencial',      ],
            ['career_id' => 42,'code'=> 'SLA20','title' => 'Comportamiento Organizacional',      ],
            ['career_id' => 42,'code'=> 'SLA21','title' => 'Derecho Privado II [Societario y Concursal]',      ],
            ['career_id' => 42,'code'=> 'SLA22','title' => 'Administración de Recursos Humanos',      ],
            ['career_id' => 42,'code'=> 'SLA23','title' => 'Tecnología de la Información',      ],
            ['career_id' => 42,'code'=> 'SLA24','title' => 'Política y Administración Financiera',      ],
            ['career_id' => 42,'code'=> 'SLA25','title' => 'Planeamiento y Estrategia',      ],
            ['career_id' => 42,'code'=> 'SLA26','title' => 'Administración de la Comercialización',      ],
            ['career_id' => 42,'code'=> 'SLA27','title' => 'Sistemas de Información Tributaria',      ],
            ['career_id' => 42,'code'=> 'SLA28','title' => 'Administración de la Producción',      ],
            ['career_id' => 42,'code'=> 'SLA29','title' => 'Desarrollo Económico y Contexto Geoempresario',      ],
            ['career_id' => 42,'code'=> 'SLA30','title' => 'Auditoria Operativa y Estratégica',      ],
            ['career_id' => 43,'code'=> 'SLE01','title' => 'Matemática I',      ],
            ['career_id' => 43,'code'=> 'SLE02','title' => 'Economía I',      ],
            ['career_id' => 43,'code'=> 'SLE03','title' => 'Sistemas de Información Contable I',      ],
            ['career_id' => 43,'code'=> 'SLE04','title' => 'Metetodología de Estudio de las Ciencias Soci',      ],
            ['career_id' => 43,'code'=> 'SLE05','title' => 'Sistemas de Información Contable II',      ],
            ['career_id' => 43,'code'=> 'SLE06','title' => 'Economía II',      ],
            ['career_id' => 43,'code'=> 'SLE07','title' => 'Matemática II',      ],
            ['career_id' => 43,'code'=> 'SLE08','title' => 'Filosofía',      ],
            ['career_id' => 43,'code'=> 'SLE09','title' => 'Administración I',      ],
            ['career_id' => 43,'code'=> 'SLE10','title' => 'Derecho Público',      ],
            ['career_id' => 43,'code'=> 'SLE11','title' => 'Estadística',      ],
            ['career_id' => 43,'code'=> 'SLE12','title' => 'Sistemas de Información Contable III',      ],
            ['career_id' => 43,'code'=> 'SLE13','title' => 'Derecho Privado I –parte general-',      ],
            ['career_id' => 43,'code'=> 'SLE14','title' => 'Informática Básica Aplicada',      ],
            ['career_id' => 43,'code'=> 'SLE15','title' => 'Administración II',      ],
            ['career_id' => 43,'code'=> 'SLE16','title' => 'Economía III',      ],
            ['career_id' => 43,'code'=> 'SLE17','title' => 'Sociología',      ],
            ['career_id' => 43,'code'=> 'SLE18','title' => 'Microeconomía I',      ],
            ['career_id' => 43,'code'=> 'SLE19','title' => 'Macroeconomía',      ],
            ['career_id' => 43,'code'=> 'SLE20','title' => 'Historia Social y Económica',      ],
            ['career_id' => 43,'code'=> 'SLE21','title' => 'Estadística para Economistas',      ],
            ['career_id' => 43,'code'=> 'SLE22','title' => 'Microeconomía II',      ],
            ['career_id' => 43,'code'=> 'SLE23','title' => 'Cálculo Financiero y Actuarial',      ],
            ['career_id' => 43,'code'=> 'SLE24','title' => 'Cálculo Financiero y Actuarial',      ],
            ['career_id' => 43,'code'=> 'SLE25','title' => 'Economía Internacional',      ],
            ['career_id' => 43,'code'=> 'SLE26','title' => 'Desarrollo Económico',      ],
            ['career_id' => 43,'code'=> 'SLE27','title' => 'Finanzas Públicas',      ],
            ['career_id' => 43,'code'=> 'SLE28','title' => 'Evaluación de Proyectos de Inversión',      ],
            ['career_id' => 43,'code'=> 'SLE29','title' => 'Econometría',      ],
            ['career_id' => 43,'code'=> 'SLE30','title' => 'Economía Monetaria',      ],
            ['career_id' => 43,'code'=> 'SLE31','title' => 'Política Fiscal',      ],
            ['career_id' => 43,'code'=> 'SLE32','title' => 'Historia del Pensamiento Económico',      ],
            ['career_id' => 43,'code'=> 'SLE33','title' => 'Política Económica Argentina',      ],
            ['career_id' => 27,'code'=> 'SOD01','title' => 'Anatomía Humana',      ],
            ['career_id' => 27,'code'=> 'SOD02','title' => 'Histología y Embriología',      ],
            ['career_id' => 27,'code'=> 'SOD03','title' => 'Química Biológica',      ],
            ['career_id' => 27,'code'=> 'SOD04','title' => 'Expresión Oral y Escrita',      ],
            ['career_id' => 27,'code'=> 'SOD05','title' => 'Biofísica',      ],
            ['career_id' => 27,'code'=> 'SOD06','title' => 'Inglés',      ],
            ['career_id' => 27,'code'=> 'SOD07','title' => 'Microbiología y Parasitología',      ],
            ['career_id' => 27,'code'=> 'SOD08','title' => 'Fisiología',      ],
            ['career_id' => 27,'code'=> 'SOD09','title' => 'Bioinformática',      ],
            ['career_id' => 27,'code'=> 'SOD10','title' => 'Epistemología e Investigación Científica',      ],
            ['career_id' => 27,'code'=> 'SOD11','title' => 'Anatomía Patológica',      ],
            ['career_id' => 27,'code'=> 'SOD12','title' => 'Odontología Preventiva Social I',      ],
            ['career_id' => 27,'code'=> 'SOD13','title' => 'Materiales Dentales',      ],
            ['career_id' => 27,'code'=> 'SOD14','title' => 'Filosofía Antropológica',      ],
            ['career_id' => 27,'code'=> 'SOD15','title' => 'Farmacología',      ],
            ['career_id' => 27,'code'=> 'SOD16','title' => 'Oclusión',      ],
            ['career_id' => 27,'code'=> 'SOD17','title' => 'Cirugía I',      ],
            ['career_id' => 27,'code'=> 'SOD18','title' => 'Operatoria Dental I',      ],
            ['career_id' => 27,'code'=> 'SOD19','title' => 'Diagnóstico por Imágenes',      ],
            ['career_id' => 27,'code'=> 'SOD20','title' => 'Semiología',      ],
            ['career_id' => 27,'code'=> 'SOD21','title' => 'Odontología Preventiva Social II',      ],
            ['career_id' => 27,'code'=> 'SOD22','title' => 'Prótesis I',      ],
            ['career_id' => 27,'code'=> 'SOD23','title' => 'Taller Preclínico de Endodoncia',      ],
            ['career_id' => 27,'code'=> 'SOD24','title' => 'Endodoncia',      ],
            ['career_id' => 27,'code'=> 'SOD25','title' => 'Periodoncia',      ],
            ['career_id' => 27,'code'=> 'SOD26','title' => 'Cirugía II',      ],
            ['career_id' => 27,'code'=> 'SOD27','title' => 'Operatoria Dental II',      ],
            ['career_id' => 27,'code'=> 'SOD28','title' => 'Clínica Estomatológica',      ],
            ['career_id' => 27,'code'=> 'SOD29','title' => 'Prótesis II',      ],
            ['career_id' => 27,'code'=> 'SOD30','title' => 'Psicología',      ],
            ['career_id' => 27,'code'=> 'SOD31','title' => 'Odontopediatría',      ],
            ['career_id' => 27,'code'=> 'SOD32','title' => 'Cirugía III',      ],
            ['career_id' => 27,'code'=> 'SOD33','title' => 'Ortodoncia',      ],
            ['career_id' => 27,'code'=> 'SOD34','title' => 'Prótesis III',      ],
            ['career_id' => 27,'code'=> 'SOD35','title' => 'Ejercicio Ético y Profesional',      ],
            ['career_id' => 12,'code'=> 'AG22','title' => 'Agro V',    ],
            ['career_id' => 12,'code'=> 'AG23','title' => 'Agro V',    ]
        ]);
        
    }
}




